{
 "title": "New dashboard",
 "time": { "from": "2024-02-14T20:38:57.248Z", "to": "2024-02-14T21:20:46.844Z" },
 "templating": {
  "list": [
   {
    "name": "uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum,uri)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum,method)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum,status)"
    }
   },
   {
    "name": "path",
    "query": {
     "query": "label_values(nginx_ingress_controller_request_duration_seconds_sum,path)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(nginx_ingress_controller_request_duration_seconds_sum,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch data (SELECT) / Insert data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=\"users_db\"} != 0",
       "legendFormat": "Fetch data"
      },
      {
       "expr": "pg_stat_database_tup_inserted{datname=\"users_db\"} != 0",
       "legendFormat": "Insert data"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage, Mb",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{pod=~\"user-service.*\"}/ 1024/1024",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{pod=~\"user-service.*\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Latency, ms (ingress)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"${path}\", method=\"${method}\",service=\"${service}\"}[$__rate_interval]))) * 1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"${path}\", method=\"${method}\",service=\"${service}\"}[$__rate_interval]))) * 1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"${path}\", method=\"${method}\", service=\"${service}\"}[$__rate_interval]))) * 1000",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "RPS (ingress)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{path=\"${path}\", service=\"${service}\", method=\"${method}\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Latency ms",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{uri=\"${uri}\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=\"${uri}\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=\"${uri}\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=~\"/user.*\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Error rate 5xx | 4xx (ingress)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{path=\"${path}\", status=~\"5.*|4.*\", service=\"${service}\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Error  rate 5xx | 4xx ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate (http_server_requests_seconds_count{uri=~\"${uri}\", status=~\"5.*|4.*\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Error count by status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_ingress_controller_request_duration_seconds_count{status=~\"5.*|4.*\"}",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  }
 ]
}